### ISSUE TITLE
Implement ESPER-specific probing/pings

### ISSUE THREAD

**Issue by motin** [motin/esper-pioneer-shield-study#1]
PHD: https://docs.google.com/document/d/1y3MSF_azfrAoKdj00_GEhC_o8sGetEuLLnloYBpVtNo/edit?ts=59ccadd2&pli=1

Relevant part:

> Appendix (telemetry fields to be collected):
> Meta
> geo_country, geo_city, normalized_channel, app_version
> 
> Profile
> profile_creation_date, profile_subsession_counter, subsession_start_date, timezone_offset
> 
> System
> os, os_version, system.memory_mb, system_cpu.cores, system_cpu.speed_mhz, system_gfx.monitors[1].screen_width
>     
> Simple Measures
> uptime, total_time, default_search_engine, locale
> 
> 
> Histograms
> places_bookmarks_count, places_pages_count, search_counts
> 
> Scalars
> Scalar_parent_browser_engagement_max_concurrent_tab_count, scalar_parent_browser_engagement_max_concurrent_window_count, scalar_parent_browser_engagement_navigation_about_newtab, scalar_parent_browser_engagement_navigation_contextmenu, scalar_parent_browser_engagement_navigation_searchbar, 
> scalar_parent_browser_engagement_navigation_urlbar,
> scalar_parent_browser_engagement_tab_open_event_count,
> scalar_parent_browser_engagement_total_uri_count, scalar_parent_browser_engagement_unfiltered_uri_count,
> Scalar_parent_browser_engagement_unique_domains_count,
> scalar_parent_browser_engagement_window_open_event_count
> 

Here is the WIP doc mapping required stmo.mozilla.org indicators and actual add-on probing: https://docs.google.com/spreadsheets/d/1COo7Cl0kMuEhAD_X25jQH2XP0owYX1gXdpbWvMmsnLw/edit#gid=0

**Comment by gregglind** [comment]
Are these all in main ping?

**Comment by motin** [comment]
Yes, they are all collected in one way or another through the main ping / ordinary telemetry, but ordinary telemetry only guarantees the collection of all probes over a longer period of time. For this study, we need to duplicate the probes that are already present in the main ping, and make sure these probes has values before submitting the esper payload. 

(We do not need to duplicate the probes that are based on environment, since environment information is supplied in the shield ping envelope.)
