### ISSUE TITLE
Make sure this addon complies with Pioneer ToS

### ISSUE THREAD

**Issue by rehandalal** [motin/esper-pioneer-shield-study#10]
Specifically we should be using [pioneer-utils](https://github.com/mozilla/pioneer-utils/) to ensure that all the data is encrypted as per this line of the ToS:

>  "The data you submit is encrypted in Firefox and not decrypted until it is on a server that is not connected to the wider internet."

**Comment by lonnen** [comment]
Hey Fred -- when I first thought about this it seemed like it wouldn't be an issue because we aren't collecting sensitive data. We put in the ToS that pioneer studies would be encrypted and we should consider that here.

sorry for the late breaking catch

**Comment by motin** [comment]
@lonnen No problem at all :)
@rehandalal Does "The data" include all telemetry sent by the add-on, or only Pioneer-specific payloads?
Today, ShieldUtils sends "installed" and "enter" pings before the study-specific pings are transmitted.

**Comment by rehandalal** [comment]
It does include *all* data. pioneer-utils does also send some pings for uninstall events (https://github.com/mozilla/pioneer-utils/blob/master/src/PioneerUtils.jsm#L20) but we can extend this to include other events.

**Comment by rehandalal** [comment]
You will also need to create schema(s) for the data you are sending through:
https://github.com/mozilla-services/mozilla-pipeline-schemas/tree/master/schemas/pioneer-study

**Comment by gregglind** [comment]
Encryping shield pings requires a major revision to how studyUtils works.
If we are going this route, your fastest path is to remove the studyUtils
lib completely.

**Comment by rehandalal** [comment]
Yeah sorry I should have been more specific about that. Use pioneer-utils insted of shield-studies-addon-utils.

**Comment by motin** [comment]
@mythmon @rehandalal - any of you want to review the PR before I merge it?

**Comment by motin** [comment]
Updated testplan docs are available here: https://github.com/motin/esper-pioneer-shield-study/blob/use-pioneer-utils/TESTPLAN.md and xpi is attached for signing at https://bugzilla.mozilla.org/show_bug.cgi?id=1414900

**Comment by motin** [comment]
@rehandalal Thanks for the review. Pushed various changes. Would you say that the add-on complies with Pioneer ToS now?
