### ISSUE TITLE
Linter for Telemetry schema

### ISSUE THREAD

**Issue by pdehaan** [motin/esper-pioneer-shield-study#16]
Not sure what [if anything] the [./schemas/esper-study-telemetry.1.schema.json](https://github.com/motin/esper-pioneer-shield-study/blob/master/schemas/esper-study-telemetry.1.schema.json) and [./schemas/esper-study-telemetry.1.sample.json](https://github.com/motin/esper-pioneer-shield-study/blob/master/schemas/esper-study-telemetry.1.sample.json) files are for, but I wrote a quick [**ajv**](http://npm.im/ajv) schema validator for the data to make sure everything was in sync:

```js
const Ajv = require('ajv');
const metaSchema = require('ajv/lib/refs/json-schema-draft-04.json');

const data = require('../schemas/esper-study-telemetry.1.sample.json');
const schema = require('../schemas/esper-study-telemetry.1.schema.json');

const ajv = new Ajv({
  allErrors: true,
});
ajv.addMetaSchema(metaSchema);

const validate = ajv.compile(schema);

if (!validate(data)) {
  const txt = ajv.errorsText(validate.errors);
  console.error(txt.split(", ").join("\n"));
  process.exitCode = 1;
}
```

Feel free to close this. I was just posting it because it took me a bit of searching to figure out why the v4 schema was throwing the following error:

> _Error: no schema with key or ref "http://json-schema.org/draft-04/schema#"_

**Comment by motin** [comment]
Supernice, thanks! 
The schema and sample file in this repo are included for reference only. The master version of the schema is found at https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/schemas/pioneer-study/esper-study-telemetry.1.schema.json and subsequently validated in that repo. 
To have automated schema validation in the add-on is definitely something we will build into the updated utils.
