### ISSUE TITLE
Parameter 'aChannel' uses Hungarian Notation, consider using 'channel' instead  (mozilla/no-aArgs)

### ISSUE THREAD

**Issue by pdehaan** [motin/esper-pioneer-shield-study#17]
```sh
$ npm run eslint

> esper-pioneer-shield-study@1.0.4 eslint /Users/pdehaan/dev/github/mozilla/esper-pioneer-shield-study
> eslint . --ext=jsm,js,json

/Users/pdehaan/dev/github/mozilla/esper-pioneer-shield-study/addon/lib/StudyTelemetryCollector.jsm
  218:38  warning  Parameter 'aChannel' uses Hungarian Notation, consider using 'channel' instead  mozilla/no-aArgs
```

Looks like the warning is coming from https://github.com/motin/esper-pioneer-shield-study/blob/552d2c7f6aef2a31c426e1c7e8082215936bca22/addon/lib/StudyTelemetryCollector.jsm#L218-L223

Looks like the easy fix is to add an `// eslint-disable-next-line` style comment to ignore that one rule for that one specific line (or, rename function arguments...):

```js
// eslint-disable-next-line mozilla/no-aArgs
function getParentProcessScalars(aChannel, aKeyed = false, aClear = false) {
  ...
}
```

**Comment by motin** [comment]
The code is copied from specific parts of the Firefox source tree and kept as-is in this add-on. Great solve to disable linting for these on a line-by-line basis.
