### ISSUE TITLE
Thought experiment:  What should be in a study-specific readme?

### ISSUE THREAD

**Issue by gregglind** [motin/esper-pioneer-shield-study#3]
Claim:

- [ ] description of goal
- [ ] list of files
- [ ] list of variations
- [ ] links to TELEMETRY and TESTPLAN
- [ ] bug number?  Maybe this should be in the description as well?
- [ ] build / run instructions?

Probably not:

- [ ] how to contribute?  

Other thoughts welcome... we are trying to pave this path.
- claim should name / id of the study have both pioneer and shield in them?  @esper-pioneer-shield-mozilla?   This makes regex searching by id have a hope of succeeding :)

**Comment by motin** [comment]
Discussion moved to https://github.com/mozilla/shield-studies-addon-template/issues/26
