### ISSUE TITLE
Get the add-on ready for QA

### ISSUE THREAD

**Issue by motin** [motin/esper-pioneer-shield-study#4]
Checklist before submitting for QA:

- [x] [PR](https://github.com/motin/esper-pioneer-shield-study/pull/2) Reviewed by Gregg @gregglind 
- [x] Bonus: PR Reviewed by Alessio @Dexterp37  (thanks! :) )
- [x] Confirmation that ESPER pings [ends up in Redash](https://sql.telemetry.mozilla.org/queries/48557/source)
- [x] Tested by me
- [ ] Tested by Gregg
- [x] Tested by Martin
- [x] Tested by Alessio
- [ ] Confirmation from Gregg that the shield utils ensures that study install event only fires once, so that the esper pings will only be sent once (otherwise: Make sure manually (using add-on-specific config) that the esper pings will only be sent once)

"Tested" here refers to following the [test plan](https://github.com/motin/esper-pioneer-shield-study/blob/prepare-for-qa/TESTPLAN.md) (Note that it is in the prepare-for-qa branch)

**Comment by mlopatka** [comment]
Following your test plan I get the following error when loading the temporary addon:

> There was an error during installation: Add-on esper-pioneer-shield-study@shield.mozilla.com is not compatible with application version. add-on minVersion: 57.0. add-on maxVersion: *.

I'm on the Beta channel using 57.0b12 (64-bit) 

I was abel to successfully load the addon in 57.0b13 (64-bit) Dev Edition.

**Comment by motin** [comment]
@mlopatka Good catch! Try the latest version (0.1.0) in the prepare-for-qa branch:

```
$ git clone https://github.com/motin/esper-pioneer-shield-study.git -b prepare-for-qa
```

I verified that it installs and executes properly in ff 56.

**Comment by mlopatka** [comment]
Installs and behaves as expected on 57.0b13 (64-bit) Dev Edition, but pings are not detected in Re:dash 30 minutes after test plan completion.

**Comment by mlopatka** [comment]
Pings arrived in re:dash query, not sure about the true latency but it is >90 minutes. Not a blocker, just useful to know when planning the deployment, collection, and analysis life-cycle of this experiment.

Comment 1 can get an r+ from me for 57.0b13 (64-bit) Dev Edition.

Has anyone had success in Release/Beta/Nightly current builds of FX?

**Comment by Dexterp37** [comment]
The ping seems to contain the correct data, as expected.

**Comment by motin** [comment]
Bug filed for QA: https://bugzilla.mozilla.org/show_bug.cgi?id=1414900
